# Generated by Django 5.0.14 on 2025-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incidents",
            "0002_incident_assigned_technician_incident_attempt_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Actif"),
                    ("IN_PROGRESS", "En cours"),
                    ("ESCALATED", "Escaladé"),
                    ("RESOLVED", "Résolu"),
                    ("ARCHIVED", "Archivé"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incidenthistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Incident créé"),
                    ("NOTIFIED", "Technicien notifié"),
                    ("ACCEPTED", "Intervention acceptée"),
                    ("REFUSED", "Intervention refusée"),
                    ("ESCALATED", "Incident escaladé"),
                    ("RESOLVED", "Incident résolu"),
                    ("ARCHIVED", "Incident archivé"),
                    ("COMMENT", "Commentaire ajouté"),
                ],
                max_length=20,
            ),
        ),
    ]
